version: '3.8'

services:
  app:
    build:
        context: .
        dockerfile: ./Dockerfile
    container_name: laravel_app
    working_dir: /var/www
    volumes:
      - ./:/var/www:z
    networks:
      - laravel_network

  web:
    image: nginx:alpine
    container_name: laravel_web
    ports:
      - 8000:80
    volumes:
      - ./:/var/www:z
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:Z
    depends_on:
      - app
    networks:
      - laravel_network

  db:
    image: mysql:8.0
    container_name: laravel_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - laravel_network

volumes:
  db_data:

networks:
  laravel_network:

